export const enum ConfigEnum {
  // Server
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  PREFIX = 'PREFIX',
  VERSION = 'VERSION',

  // Database
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',

  // Redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  // Logs
  LOG_DIR = 'LOG_DIR',
  LOG_DATE_FORMAT = 'LOG_DATE_FORMAT',
  LOG_ZIPPED_ARCHIVE = 'LOG_ZIPPED_ARCHIVE',
  LOG_MAX_SIZE = 'LOG_MAX_SIZE',
  LOG_MAX_FILES = 'LOG_MAX_FILES',
  LOG_ON = 'LOG_ON',

  // Feature switches
  ALL_EXCEPTION_FILTER = 'ALL_EXCEPTION_FILTER',
  CORS = 'CORS',

  // Mail
  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_USERNAME = 'MAIL_USERNAME',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MAIL_FROM_EMAIL = 'MAIL_FROM_EMAIL',
  MAIL_FROM_NAME = 'MAIL_FROM_NAME',
}
